### ISSUE TITLE
Include index_name in Weviate example. 

### ISSUE THREAD

**Issue by jackpaulcollins** [andreibondarev/langchainrb#117]
A small improvement to the docs for the Weaviate example is to include index_name 

```ruby
client = Langchain::Vectorsearch::Weaviate.new(
    url: ENV["WEAVIATE_URL"],
    api_key: ENV["WEAVIATE_API_KEY"],
    index_name: "Document", # add this
    llm: :openai, # or :cohere
    llm_api_key: ENV["OPENAI_API_KEY"]
)
```
Since this is required by the API it makes sense to include

Reference: https://weaviate.io/developers/weaviate/quickstart/custom-vectors#schema

**Comment by andreibondarev** [comment]
@jackpaulcollins Good catch!
