### ISSUE TITLE
Calculate max_tokens based on model and prompt token values

### ISSUE THREAD

**Issue by mattlindsey** [andreibondarev/langchainrb#123]
Prompt + completion is apparently sometimes exceeding with hardcoded max_token values in the agents.
I think it can be calculated as: model_limit - prompt_token_size.  
Use the Utils class TokenLengthValidator and/or Tiktoken.

(https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb) for counting tokens.](https://platform.openai.com/docs/api-reference/completions/create#completions/create-max_tokens)

**Comment by mattlindsey** [comment]
Seems like maybe the tiktoken_ruby gem should provide this value, since it already knows about the different openai models.  It would be the place to keep TOKEN_LIMITS (instead of Langchain::Utils, where they are now) and it would calculate max_tokens, rather than langchainrb.  
Langchain would still have a 'validate' method, but maybe in Langchain::LLM rather than Langchain::Utils?

Worth opening an Issue or PR here? https://github.com/IAPark/tiktoken_ruby

**Comment by andreibondarev** [comment]
@mattlindsey Yeah, I was wondering that too. I think it's worth asking why they're not maintaining the token limits in their lib?  I had fished [these](https://github.com/andreibondarev/langchainrb/blob/main/lib/langchain/utils/token_length_validator.rb#L14-L35) out from the docs.
