### ISSUE TITLE
[Proposal] Add a processor to import xlsx files

### ISSUE THREAD

**Issue by ProGM** [andreibondarev/langchainrb#128]
It should be pretty straight forward using the [xsv](https://github.com/martijn/xsv) gem.

Something like (untested):
```ruby
# frozen_string_literal: true

require "xsv"

module Langchain
  module Processors
    class Xlsx < Base
      EXTENSIONS = [".xlsx"]
      CONTENT_TYPES = ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]

      # Parse the document and return the text
      # @param [File] data
      # @return [Array of Hash]
      def parse(data)
        xlsx_file = Xsv.open(data.read)
        xlsx_file.sheets.flat_map do |sheet|
          sheet.map do |row|
            row.map(&:strip)
          end
        end
     end
  end
end
```

**Comment by andreibondarev** [comment]
@ProGM This makes sense to me! Do you want to take a stab at it? 

@alchaplinsky Any input from you?

**Comment by ProGM** [comment]
@andreibondarev yup!

After a brief research, I think it may make sense to use [roo](https://github.com/roo-rb/roo) instead of xsv. It's much more used (2,7k stars vs ~180) and supports also OpenOffice sheets.

What do you think?
