### ISSUE TITLE
[Feature Request] 🤖 Agents should accept `memory:` option

### ISSUE THREAD

**Issue by andreibondarev** [andreibondarev/langchainrb#129]
### Description: 
Agents need to be able to store data in memory or vector search DB for retrieval later.

### Example:
There's a limitation with the current `SQLQueryAgent` agent that will encounter a context window limit when a large database table schema is passed in to the LLM. As [pointed out](https://github.com/andreibondarev/langchainrb/pull/91#discussion_r1214217270) by @bborn LlamaIndex stores the DB schema in a vector search database to avoid stuffing the whole DB schema in a single prompt.

We should make the `memory:` (should we call it `persistence:` instead?) to Agents to solve problems like that ^^

**Comment by mattlindsey** [comment]
Do any of the supported vector search databases run locally?  I'd like to try adding one to `SQLQueryAgent` and I think it would be nice to develop with both my local sql database and a local vector search database.

**Comment by andreibondarev** [comment]
For the cases when the DB schema is too large, unlike LlamaIndex writing to a DB index, I'm actually thinking of implementing it in memory; been looking at Faiss.

**Comment by bborn** [comment]
@andreibondarev in-memory seems fine, but just keep in mind caching ... would be nice to not have to rebuild the DB schema index every time (in a web app where requests are stateless). Maybe something configurable that defaults to in-memory but can be swapped easily (e.g. pass in any `Langchain::Vectorsearch` instance)?

**Comment by andreibondarev** [comment]
@bborn Checkout this light-weight vector search implementation I'm prototyping: https://github.com/andreibondarev/langchainrb/pull/150/files

There's an option to persist to disk with:
```ruby
client.save_index('index_name.ann')
client.load_index('index_name.ann')
```

Specifically for the [SQLQueryAgent](https://github.com/andreibondarev/langchainrb/blob/main/lib/langchain/agent/sql_query_agent/sql_query_agent.rb) and the issue where the DB schema is too large (the "let's store it, vector search over it, and only provide the DB tables the LLM needs to generate the query") -- this is what I'm thinking:

1. We need a way to represent the DB schema as a data structure, something like:
```ruby
db_schemas = [
  { id:, table_name: "users", columns: ["id(pk)", "first_name(string)", ... , "org_id(fk)"]
  ...
]
```
We'd either, also, persist it or keep it in-memory.
2. We'd then create vector embedding from these db_schemas:
```ruby
hnsw.add_texts texts: db_schemas, ids: db_schemas.collect { |r| r[:id] } 
```
3. When retrieved we'd do the KNN search, get the IDs and match them back to the `db_schemas` records.
```ruby
ids = hnsw.search_knn(embedding, k)

tables_to_send_to_LLM = db_schemas.find { |record| ids.include?(record[:id]} 
```

The only thing I'm unclear about is whether and how to persist `db_schemas = []`.

**Comment by bborn** [comment]
@andreibondarev cool! Hmm... could you store the table name instead of an id? Then maybe you could just dump the schemas for those tables on the fly and not have to store them anywhere...

**Comment by andreibondarev** [comment]
> @andreibondarev cool! Hmm... could you store the table name instead of an id? Then maybe you could just dump the schemas for those tables on the fly and not have to store them anywhere...

Nope, it only accepts integers :/
