### ISSUE TITLE
[Proposal] Option to persist conversations when using chat endpoints

### ISSUE THREAD

**Issue by andreibondarev** [andreibondarev/langchainrb#136]
### Background
Currently the conversations with LLMs that offer the `.chat()` endpoint are not persisted, hence the LLM has no context of the previous chat messages that may have taken place.

The following 2 LLMs offer chat capabilities and accept `messages:` array:
* Google Palm: [API specs](https://developers.generativeai.google/api/python/google/generativeai/chat) and Ruby client [endpoint](https://github.com/andreibondarev/google_palm_api/blob/main/lib/google_palm_api/client.rb#L91).
* OpenAI: https://platform.openai.com/docs/api-reference/chat/create#chat/create-messages.

### Tasks:
* Modify the Google Palm and OpenAI LLM `.chat()` methods to persist and keep track of previous chat exchanges that has taken place.

### Open Questions:
1. What is the best way to persist these conversations? That fits well with the langchain.rb library. In-memory, DB, vectorsearch DB, Redis?
2. What does the interface look like? Possibly:
```ruby
openai = Langchain::LLM::OpenAI.new(api_key: ENV["OPENAI_API_KEY"])

openai.chat_persistence = true

openai.ask(question: ...)
#=> LLM answer...
openai.ask(question: ...)
#=> LLM answer...
openai.ask(question: ...)
#=> LLM answer...

openai.clear_chat_persistence!

openai.chat_persistence = false
```

**Comment by alchaplinsky** [comment]
working on it.

**Comment by zewelor** [comment]
One thing that came into mind. Maybe chat should be separate object ? For example if you want to have 2 conversations ( imagine bots talking to each other, each with different chat ? ). It wont be possible now ? Or probalby other cases.

What about something like:

```
openai = Langchain::LLM::OpenAI.new(api_key: ENV["OPENAI_API_KEY"])
chat1 = openai.start_chat ( or new_chat or whatever )
chat1.ask().

chat2 = openai.start_chat
chat2.ask()

```

**Comment by oluvvafemi** [comment]
Could we do something like `ConversationChain` in Langchain? This way, we could use different types of conversational memory with it like `ConversationBufferMemory` or `ConversationSummaryMemory`.

```
conversation_buf = ConversationChain(
    llm=llm,
    memory=ConversationBufferMemory()
)
```

**Comment by andreibondarev** [comment]
> Could we do something like `ConversationChain` in Langchain? This way, we could use different types of conversational memory with it like `ConversationBufferMemory` or `ConversationSummaryMemory`.
> 
> ```
> conversation_buf = ConversationChain(
>     llm=llm,
>     memory=ConversationBufferMemory()
> )
> ```

@oluvvafemi Do you have a specific use-case or requirement here?

I think @alchaplinsky is building out the initial version to just use In-Memory store behind the scenes and then we'll think about what the next iteration looks like.

**Comment by oluvvafemi** [comment]
> > Could we do something like `ConversationChain` in Langchain? This way, we could use different types of conversational memory with it like `ConversationBufferMemory` or `ConversationSummaryMemory`.
> > ```
> > conversation_buf = ConversationChain(
> >     llm=llm,
> >     memory=ConversationBufferMemory()
> > )
> > ```
> 
> @oluvvafemi Do you have a specific use-case or requirement here?
> 
> I think @alchaplinsky is building out the initial version to just use In-Memory store behind the scenes and then we'll think about what the next iteration looks like.

Yes, I would like to keep conversation memory for a chatbot.

**Comment by alchaplinsky** [comment]
Added a higher-level `Langchain::Chat` concept https://github.com/andreibondarev/langchainrb/pull/160. An instance of a `Chat` keeps all messages in memory. It also can will be able to receive message history obtained from the DB or any other storage. As an option it might have capabilities of working with different storages internally.

**Comment by andreibondarev** [comment]
@zewelor @oluvvafemi Would you please try out the new `Langchain::Chat` interface? The chat history is persisted in memory now. 
```ruby
llm = Langchain::LLM::OpenAI.new(api_key: ENV['OPENAI_API_KEY'])
chat_session = Langchain::Chat.new(llm: llm)

chat_session.set_context("You are a travel agent AI. You help the user create travel itineraries.")

chat_session.message("Please give me a 3-day itinerary for a weekend visit to Paris")
```

Please let us know your feedback!

**Comment by mattlindsey** [comment]
Looks nice to me!  I like the name `Langchain::Converstion` since there's a context(optional) and history involved and avoids confusion with just calling 'chat' on the llm directly.

**Comment by alchaplinsky** [comment]
Hmm.. I actually like `Conversation` more than `Chat`. I think it is a more suitable name even though it is more characters to type. WDYT @andreibondarev?

**Comment by alchaplinsky** [comment]
Created a PR with voting for the change: https://github.com/andreibondarev/langchainrb/pull/168

**Comment by oluvvafemi** [comment]
> @zewelor @oluvvafemi Would you please try out the new `Langchain::Chat` interface? The chat history is persisted in memory now.
> 
> ```ruby
> llm = Langchain::LLM::OpenAI.new(api_key: ENV['OPENAI_API_KEY'])
> chat_session = Langchain::Chat.new(llm: llm)
> 
> chat_session.set_context("You are a travel agent AI. You help the user create travel itineraries.")
> 
> chat_session.message("Please give me a 3-day itinerary for a weekend visit to Paris")
> ```
> 
> Please let us know your feedback!
> 
> (Credit to @alchaplinsky for building this out!)

Good job @alchaplinsky. I created PR #172 to add attr_reader for messages.

**Comment by andreibondarev** [comment]
@oluvvafemi Where do you plan saving your chat messages? To disk or DB?

**Comment by andreibondarev** [comment]
The persistence should be done via the new `Langchain::Thread` and `Langchain::Message` classes.
