### ISSUE TITLE
[Proposal] Improvements to the ChainOfThoughtAgent

### ISSUE THREAD

**Issue by andreibondarev** [andreibondarev/langchainrb#177]
~~1. Rename `ChainOfThoughtAgent` to `ReActAgent` because that's what it actually is. This is what "chain of thought" is: https://learnprompting.org/docs/intermediate/chain_of_thought; and this is what "ReAct" actually is: https://arxiv.org/abs/2210.03629~~
2. Try asking the LLM for a JSON output format -- may or may not be more accurate. Source: 
<img width="1504" alt="image" src="https://github.com/andreibondarev/langchainrb/assets/541665/5eaf8063-d265-468f-9f4f-a448bd0f0df7">. i.e. instead of [RegEx-ing strings](https://github.com/andreibondarev/langchainrb/blob/main/lib/langchain/agent/chain_of_thought_agent/chain_of_thought_agent.rb#L70), we may be able to read off JSON keys instead.

(Separate PRs please).

**Comment by mattlindsey** [comment]
Improvement 2 sounds nice since subsequent calls to the llm `complete` will add llm responses grouped in JSON clumps, which will be easier to understand.

**Comment by mattlindsey** [comment]
How about I do 1 PR to rename the agents to ReAct and SQLQueryChain?

**Comment by andreibondarev** [comment]
"SqlQueryAgent" doesn't work anymore? I'd like to refer or avoid the notion of "chains" for the time being.

**Comment by mattlindsey** [comment]
My feeling is SQLQueryAgent really isn't semi-autonomous being limited to 2 steps and 1 tool, but that could change. So that's fine.

**Comment by arthurhess** [comment]
Hi! I'm new to this project and I'd love to work on these. May I?
