### ISSUE TITLE
Error in validate_max_tokens using Google Palm llm

### ISSUE THREAD

**Issue by mattlindsey** [andreibondarev/langchainrb#178]
<img width="1075" alt="image" src="https://github.com/andreibondarev/langchainrb/assets/5638339/7d30bed5-26cc-46d0-9e85-5a0e03c58cf1">

Using a new API key from google that works from `curl`, I get the error above using a simple prompt.

Also `summarize`, `complete`, and `embed` return `nil`.

**Comment by andreibondarev** [comment]
@mattlindsey I just tried it out:
<img width="1600" alt="image" src="https://github.com/andreibondarev/langchainrb/assets/541665/45da6bb8-ee5b-475f-9df8-2df755dce3ce">

Did you get the key from here? https://developers.generativeai.google/products/palm?authuser=1

**Comment by andreibondarev** [comment]
Works for me: 
<img width="774" alt="image" src="https://github.com/andreibondarev/langchainrb/assets/541665/979e5158-75fd-4707-94db-945df2973684">

**Comment by mattlindsey** [comment]
Resolved.  Creating object improperly:
<img width="528" alt="image" src="https://github.com/andreibondarev/langchainrb/assets/5638339/f7b75bcc-3730-4693-8ca7-8f75c70d8f1c">
