### ISSUE TITLE
Add chat streaming to Google PaLM (if possible)

### ISSUE THREAD

**Issue by andreibondarev** [andreibondarev/langchainrb#183]
Currently `Langchain::LLM::OpenAI` is the only adapter that supports streaming chat replies by passing the block to the `.chat()` call:
```ruby
chat = Langchain::Conversation.new(llm: llm) do |chunk|
  print(chunk)
end
```

Google PaLM API support `chat_async`: https://developers.generativeai.google/api/python/google/generativeai/chat_async?authuser=1. It is unclear whether it would work the same way as the OpenAI. 

It probably involves making a change to https://github.com/andreibondarev/google_palm_api.

**Comment by alchaplinsky** [comment]
Google PaLM API doesn't seem to support streaming atm.

**Comment by andreibondarev** [comment]
@alchaplinsky I think it needs to be done at the gem level. Take a look at this: https://lostisland.github.io/faraday/usage/streaming

**Comment by alchaplinsky** [comment]
@andreibondarev I mean, sure you can re-write a client call that way, but you'll just get 1 chunk with the complete response if the backend does not support streaming. And it seems that there's no streaming option in the API: https://developers.generativeai.google/api/python/google/generativeai/generate_text?authuser=1

**Comment by andreibondarev** [comment]
@alchaplinsky True, unless it's supported but not documented.

**Comment by alchaplinsky** [comment]
I've tried passing options like `stream` and `streaming`. API returns an error response with a message about an invalid option.

**Comment by alchaplinsky** [comment]
Yes, you get just one chunk whereas with OpenAI API you get each word as a chunk.

**Comment by andreibondarev** [comment]
@alchaplinsky Got it -- closing this issue for now then.
