### ISSUE TITLE
Use maybe ruby-openai ?

### ISSUE THREAD

**Issue by lumpidu** [andreibondarev/langchainrb#2]
Have you checked https://github.com/alexrudall/ruby-openai ?

**Comment by andreibondarev** [comment]
@lumpidu I haven't yet! Do you have any thoughts on how it compares against the current OpenAI we're using here?

**Comment by rickychilcott** [comment]
It seems like we are currently using that gem. Am I missing something?

**Comment by andreibondarev** [comment]
@rickychilcott D'oh! We are, I must've thought @lumpidu was talking about a different gem. There's a few OpenAI Ruby gems.
