### ISSUE TITLE
google PaLM client `generate_text': unknown keyword: :completion_model_name (ArgumentError)

### ISSUE THREAD

**Issue by jinshen-cn** [andreibondarev/langchainrb#205]
In this code https://github.com/andreibondarev/langchainrb/blob/main/lib/langchain/llm/google_palm.rb#L60-L79
Looks like it intends to pass `default_options` (which is merge into `default_params` to the `cleint.generate_text`
```ruby
    def complete(prompt:, **params)
      default_params = {
        prompt: prompt,
        temperature: @defaults[:temperature],
        completion_model_name: @defaults[:completion_model_name]
      }

      if params[:stop_sequences]
        default_params[:stop_sequences] = params.delete(:stop_sequences)
      end

      if params[:max_tokens]
        default_params[:max_output_tokens] = params.delete(:max_tokens)
      end

      default_params.merge!(params)

      response = client.generate_text(**default_params)
      response.dig("candidates", 0, "output")
    end
```

But in google client lib
https://github.com/andreibondarev/google_palm_api/blob/main/lib/google_palm_api/client.rb#L41-L51
```ruby
    def generate_text(
      prompt:,
      temperature: nil,
      candidate_count: nil,
      max_output_tokens: nil,
      top_p: nil,
      top_k: nil,
      safety_settings: nil,
      stop_sequences: nil,
      client: nil
    )
```
It doesn't accept the argument `completion_model_name`. Even further, the default model name won't be overwritten from `Langchain::LLM::GooglePalm`. Because in `GooglePalmApi::Client`, when initialize the client, it doesn't take any additional options except API key.
https://github.com/andreibondarev/google_palm_api/blob/main/lib/google_palm_api/client.rb#L12-L21
```ruby
    DEFAULTS = {
      temperature: 0.0,
      completion_model_name: "text-bison-001",
      chat_completion_model_name: "chat-bison-001",
      embeddings_model_name: "embedding-gecko-001"
    }

    def initialize(api_key:)
      @api_key = api_key
    end
```

Not only the `generate_text` method in the client, but also `generate_chat_message` and `embed`.

**Comment by andreibondarev** [comment]
@jinshen-cn Google PaLM currently only has 3 different models that support different methods:
* text-bison-001 for text completion
* chat-bison-001 for chat
* embedding-gecko-001 to generate embeddings

You can't use `text-bison-001` for chat for example.

https://developers.generativeai.google/models/language

I can modify the `google_palm_api` gem to accept `model:` but it won't change much as far as Langchain.rb is concerned.

**Comment by andreibondarev** [comment]
@jinshen-cn I went ahead and bumped up the google_palm_api gem with the fix included: https://github.com/andreibondarev/langchainrb/pull/206.

I'm closing this issue for now unless you need it open.

**Comment by jinshen-cn** [comment]
@andreibondarev thanks for the information. That make sense to hard code the model.
Then the issue is on `langchainrb` side. When calling google client from `GooglePalm`, it passes more arguments than the client accepts. That will throw out the exception `unknown keyword: :completion_model_name (ArgumentError)`
I believe the issue is brought in by this change
https://github.com/andreibondarev/langchainrb/commit/733b03720d65d34dc7dd59253d29da917dca5335#diff-ec2ba4ee1eff7b6ca445553141a680962a00955ab091df1e4fed35c98a101cb5
As it merges the `DEFAULTS` and `default_options` together
```ruby
    @defaults = DEFAULTS.merge(default_options)
```

**Comment by andreibondarev** [comment]
Ohhh, I see. The gem now takes the `model:` param but, if the `model:` is not set explicitly it'll use the default.

It sounds like [this](https://github.com/andreibondarev/langchainrb/blob/main/lib/langchain/llm/google_palm.rb#L55) and [this](https://github.com/andreibondarev/langchainrb/blob/main/lib/langchain/llm/google_palm.rb#L85) hash keys need to be changed to `model: ...`. Want to make this change?

There may or may not be a similar issue with other LLM providers.

**Comment by jinshen-cn** [comment]
Even changing the argument name to `model` won't eventually resolve the problem. We don't know what the user will put into `default_options` as we open this out. Maybe we should write as below for more tolerance.
```ruby
    def generate_text(
      prompt:,
      temperature: nil,
      candidate_count: nil,
      max_output_tokens: nil,
      top_p: nil,
      top_k: nil,
      safety_settings: nil,
      stop_sequences: nil,
      client: nil,
      **other_options
    )
```

**Comment by jinshen-cn** [comment]
> 

I think for other LLM providers, we may encounter the same issue in future if the user puts an unrecognized argument in `default_options`

**Comment by jinshen-cn** [comment]
> Ohhh, I see. The gem now takes the `model:` param but, if the `model:` is not set explicitly it'll use the default incorrect param name.
> 
> It sounds like [this](https://github.com/andreibondarev/langchainrb/blob/main/lib/langchain/llm/google_palm.rb#L55) and [this](https://github.com/andreibondarev/langchainrb/blob/main/lib/langchain/llm/google_palm.rb#L85) hash keys need to be changed to `model: ...`. Want to make this change?
> 
> There may or may not be a similar issue with other LLM providers.

I think for other LLM providers, we may encounter the same issue in future if the user puts an unrecognized argument in default_options

**Comment by andreibondarev** [comment]
@jinshen-cn So I think we can validate the keys that are passed in with something like this:
```ruby
default_options_allowed_keys = [:model, :temperature, :top_k] # + other keys

unrecognized_keys = default_options.keys - default_options_allowed_keys
raise ArgumentError, "#{unrecognized_keys}..."
```

Obviously it just needs to be refactor to nice and concise code. Maybe each method calls:
```ruby
validate_default_option_keys!(default_options.keys)
```

**Comment by andreibondarev** [comment]
@jinshen-cn Merging this temporary this in: https://github.com/andreibondarev/langchainrb/pull/210

**Comment by andreibondarev** [comment]
@jinshen-cn Also using a stronger Cohere model by default: https://github.com/andreibondarev/langchainrb/commit/309ec879147bd1ce3b33cdae097bf2937be5aad5

**Comment by andreibondarev** [comment]
I'm closing this since the original Issue was fixed.
