### ISSUE TITLE
Support latest version of OpenAi.rb

### ISSUE THREAD

**Issue by bborn** [andreibondarev/langchainrb#214]
see here: https://github.com/alexrudall/ruby-openai/blob/main/CHANGELOG.md

The newest version has a breaking change:

```Endpoints now return JSON rather than HTTParty objects. You will need to update your code to handle this change, changing JSON.parse(response.body)["key"] and response.parsed_response["key"] to just response["key"].```

**Comment by andreibondarev** [comment]
@bborn Did you mean to close this Issue?

**Comment by bborn** [comment]
@andreibondarev yeah, I thought it was broken but then realized it was something on my end.
