### ISSUE TITLE
Elasticsearch support 

### ISSUE THREAD

**Issue by sivagollapalli** [andreibondarev/langchainrb#232]
Just like other databases elastic search also comes with vector fields support and its search as described [here](https://www.elastic.co/blog/text-similarity-search-with-vectors-in-elasticsearch). Are there any plans to support this?

**Comment by andreibondarev** [comment]
@sivagollapalli Is this something you would like to use?

**Comment by sivagollapalli** [comment]
@andreibondarev Yes, since elastic search is common software that applications are used for search functionality. Since ES supports vector search in recent versions so devs generally prefer to run vector search with ES. Hence it would be good to have ES support as well. If it makes sense I will like to contribute.

**Comment by andreibondarev** [comment]
@sivagollapalli Yes, please feel free to take a stab at it!
