### ISSUE TITLE
OutputFixingParser problem?

### ISSUE THREAD

**Issue by skryking** [andreibondarev/langchainrb#274]
Hi,

So I'm not sure if this is a problem or I'm just doing something stupid.  I was following the example on using the Structured output and then using a fixing parser if its not validated correctly.  for some reason it doesn't appear to be resubmitting my context with the prompt so the response comes back as nonsense compared to what I was asking.  

`parser = Langchain::OutputParsers::StructuredOutputParser.from_json_schema(get_json_schema)

    llm = Langchain::LLM::OpenAI.new(
      api_key: Rails.application.credentials[:openai_key],
      default_options: {
        chat_completion_model_name: 'gpt-3.5-turbo-16k'
      }
    )

    llm_response = llm.chat(
      prompt: prompt.format(identity:, format_instructions: parser.get_format_instructions,
                            alteration:),
      context: context.to_json
    )

    fix_parser = Langchain::OutputParsers::OutputFixingParser.from_llm(
      llm:,
      parser:
    )`

I don't see a way to add the context in the fixing parser.  am I going about this the wrong way?

Any help would be greatly appreciated.

**Comment by andreibondarev** [comment]
@skryking I would put a debugger [here](https://github.com/andreibondarev/langchainrb/blob/main/lib/langchain/output_parsers/fix.rb#L55) and look at what actually gets sent to the LLM.

The default prompt that's used to have the LLM try and fix the invalid response is this one: https://github.com/andreibondarev/langchainrb/blob/main/lib/langchain/output_parsers/prompts/naive_fix_prompt.yaml

If it's missing the context, like you said, I would try (re-)creating your own prompt, inspired by the naive fix prompt above, and pass it directly when the initializing: 
```ruby
fix_parser = Langchain::OutputParsers::OutputFixingParser.from_llm(
  llm:,
  parser:,
  prompt: ... # <= here
)
```

**Comment by skryking** [comment]
@andreibondarev Hey thanks, that worked out well.  I was able to stick the needed context into the prompt, and it sent a correctly formatted response that made sense.

**Comment by andreibondarev** [comment]
@skryking Great... closing this issue for now!
