### ISSUE TITLE
Standard Completions aren't ideal for chat agents

### ISSUE THREAD

**Issue by merefield** [andreibondarev/langchainrb#283]
I'll just leave this here:

```
[17] pry(main)> agent.run(question: "hi")
I, [2023-08-09T18:00:53.352403 #626398]  INFO -- : [LangChain.rb] [Langchain::Agent::ReActAgent]: Sending the prompt to the Langchain::LLM::OpenAI LLM
=> "No answer."
```

😢 

Would chat completion for agents be on the roadmap?

**Comment by merefield** [comment]
Yep, we already have the capability to pursue a conversation (in fact I'm using my own framework for that), but what I'm looking for from Langchain is the ability to use agents for a conversation, so using a Chat endpoint within an Agent interaction is key.

**Comment by alchaplinsky** [comment]
@merefield I think a good approach would be to create a new type of agent, like `ConversationalAgent`, and use `Langchain::ConversationMemory` within this class in order to combine persisted messages and use of tools.

**Comment by mengqing** [comment]
Any plans to support tools in conversations soon?

**Comment by andreibondarev** [comment]
@mengqing Take a look at the `Langchain::Assistant` class: https://github.com/andreibondarev/langchainrb?tab=readme-ov-file#assistants. It can use tools in conversations.
