### ISSUE TITLE
Design a modular system where dependencies can be optionally included

### ISSUE THREAD

**Issue by andreibondarev** [andreibondarev/langchainrb#3]
### Problem:
Currently if you'd like to only use Qdrant and OpenAI, this gem will install a bunch of other dependencies you don't need. There's no reason to do this. 

### Options to consider:
We can build a similar system to `omniauth` where different strategies are installed separately `omniauth-github`, `omniauth-facebook`, etc.
We'd ask the user to install gems, on their own, in their applications and then we'd require them in this gem (pseudo-codeish):
```
class Qdrant
  def initialize
     require "qdrant"
     ...
```

Thank you for raising this issue @alchaplinsky!

**Comment by rickychilcott** [comment]
I think this is a good idea too but in these early days of this tool, I’d resist doing this right away. On approach might be to not include the various dependencies in the base gem and not require them unless they are used. That allows you to minimize required dependencies but still keep it easy to change interfaces in the near term. 

I’m thinking something similar to how Rack Mini Profiler works - https://github.com/MiniProfiler/rack-mini-profiler#installation


What do you think about that approach in the near term?

**Comment by andreibondarev** [comment]
@rickychilcott Do you mean **not** doing the whole notion of "meta gems", similar to https://github.com/zquestz/omniauth-google-oauth2/blob/master/omniauth-google-oauth2.gemspec#L25 where the gem requires the core gem?

I was thinking the simplest near-term implementation is doing something like this:
```
# README.md

### Vector Search

If you'd like to use qdrant, please install it separately:

gem "qdrant-ruby"
gem "langchainrb"
```
```
module Vectorsearch
  class Qdrant < Base
    def initialize
      require "qdrant-ruby"
   rescue LoadError => e
      raise e, "Please install `qdrant-ruby` gem if you'd like to use Qdrant"
```

**Comment by rickychilcott** [comment]
Yes exactly. I don't think we/you should take the omni-auth route for now while the interfaces of tools, agents, etc. may be changing.

I'm happy to take a stab, if you're cool with it.

**Comment by andreibondarev** [comment]
@rickychilcott Yes sir! If you want to do a quick prototype for 1-2 dependencies -- we can quickly chat through it and then move forward so if it works well!

**Comment by andreibondarev** [comment]
Related problem:
Requiring and pinning the correct gem dependency version.

Related discussion: https://github.com/rubygems/rubygems/issues/3607#issuecomment-626088347
Here's an example of loading the gem with a version as well: https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L3-L4

All this to suggest that instead of:
```
def initialize
  require "qdrant-ruby"
```
we can do
```
def initialize
  gem "qdrant-ruby", QDRANT_GEM_VERSION
```

But we need to figure out where `QDRANT_GEM_VERSION` constant, lookup JSON, hash, etc are stored.

**Comment by andreibondarev** [comment]
I tested it out really quickly here:
```ruby
 -> langchain [main*]: irb
irb(main):001:0> gem "qdrant-ruby", "~> 0.9.0"
=> true
irb(main):002:0> gem "qdrant-ruby", "~> 0.8.0"
/Users/andrei/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/rubygems/dependency.rb:309:in `to_specs': Could not find 'qdrant-ruby' (~> 0.8.0) - did find: [qdrant-ruby-0.9.2,qdrant-ruby-0.9.0] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/Users/andrei/.gem/ruby/3.0.0:/Users/andrei/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0' , execute `gem env` for more information
	from /Users/andrei/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/rubygems/dependency.rb:319:in `to_spec'
	from /Users/andrei/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_gem.rb:62:in `gem'
	from (irb):2:in `<main>'
	from /Users/andrei/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/irb-1.6.4/exe/irb:9:in `<top (required)>'
	from /Users/andrei/.asdf/installs/ruby/3.0.0/bin/irb:23:in `load'
	from /Users/andrei/.asdf/installs/ruby/3.0.0/bin/irb:23:in `<main>'
```
