### ISSUE TITLE
[Proposal] Using OpenAIs chat endpoint for completions.

### ISSUE THREAD

**Issue by d96litz** [andreibondarev/langchainrb#305]
As OpenAIs `text-davinci-xxx` is "legacy" and the GPT-X models are much cheaper and have a better quality i would propose to use the GPT models for completions as well. [Source](https://platform.openai.com/docs/models/gpt-3-5)
But as the GPT models can't be used with the `completion` API, the `chat`-API must be used.

I just tried changing `completion` to `chat` here: https://github.com/andreibondarev/langchainrb/blob/5e143657ffd1e3ef1d1a9c55fa367f7357ce107c/lib/langchain/agent/react_agent.rb#L61
and it worked perfectly (gave a much better result).

Maybe it would make sense to just use the `chat` endpoint here:
https://github.com/andreibondarev/langchainrb/blob/5e143657ffd1e3ef1d1a9c55fa367f7357ce107c/lib/langchain/llm/openai.rb#L59

I could provide a PR if it helps.
Thanks for this awesome gem btw 🙂

**Comment by alchaplinsky** [comment]
@d96litz Added a PR that switches to a `chat` endpoint for completion https://github.com/andreibondarev/langchainrb/pull/312

**Comment by andreibondarev** [comment]
@d96litz @alchaplinsky Instead of changing the method itself on LLM::OpenAI, why won't we change the method that the ReactAgent uses itself? `llm.chat` instead of `llm.complete`?

**Comment by d96litz** [comment]
But the issue legacy/price/performance applies to all forms of completion, not just for the ReactAgent. I just tried it for the agent because i was using it but people will also benefit from the GPT models outside of an agent.

If we want to prevent a breaking change we could add a switch like (want davinci => use completion endpoint, want gpt => use chat endpoint).

**Comment by d96litz** [comment]
Awesome guys, thanks. If you ever need help in this project. I'll be happy to help
