### ISSUE TITLE
Combine the functionality into a single method call.

### ISSUE THREAD

**Issue by andreibondarev** [andreibondarev/langchainrb#306]
Example: https://github.com/andreibondarev/langchainrb/blob/main/lib/langchain/llm/openai.rb#L29-L30

This type of code is repeated in many many places. Instead of having 2 lines, we should just be able to call a single method that does both `depends_on()` and `require()`.

Maybe `depends_on` itself does the require as well?

**Comment by dferrazm** [comment]
I'll take a stab at this one.
