### ISSUE TITLE
Conversation message history is broken

### ISSUE THREAD

**Issue by alchaplinsky** [andreibondarev/langchainrb#320]
## Details
Passing an array of messages as hashes to a conversation leads to errors when trying to send a message
```ruby 
messages = [
  {role: "user", message: "..."},
  {role: "ai", message: "..."},
]
conversation = Langchain::Conversation.new(llm: llm, messages: messages)
conversation.message('hello')

NoMethodError (undefined method `type' for {}:Hash
```

**Comment by drale2k** [comment]
I think you can't pass hashes directly but need to fill the array with `HumanMessage` and `AIMessage` instances. 

```ruby
human_message = HumanMessage.new("hello")
ai_message = AIMessage.new("hi")

message = [human_message, ai_message]
```

**Comment by alchaplinsky** [comment]
It was possible before this one https://github.com/andreibondarev/langchainrb/pull/276 got merged. 

I thought the idea was that `Langchain::Conversation` wraps messages internally with `HumanMessage` and `AIMessage`. But it appears that it also returns messages as instances of those classes and expects `examples` and `messages` to be that.

Anyway, `Langchain::Conversation`  constructor SHOULD NOT just silently assume that passed messages are of correct kind. And then just raise an error when you try to send a message. Conversation should either smartly wrap passed `messages` with these classes or raise an error in `initializer` that messages are of incorrect kind.
