### ISSUE TITLE
Add the `ask()` method to our `Langchain::ActiveRecord::Hooks`

### ISSUE THREAD

**Issue by andreibondarev** [andreibondarev/langchainrb#345]
### Motivation
We'd like to expose the `ask()` method so that you can utilize the RAG (Retrieval Augmented Generation) flow when operating on the ActiveRecord model.

### Steps
In the `Langchain::ActiveRecord::Hooks` class, similar to the [similarity_search()](https://github.com/andreibondarev/langchainrb/blob/main/lib/langchain/active_record/hooks.rb#L85-L94) method we should expose the `ask()` method. 
This method should be just forwarding the `ask()` method along to the vectorsearch provider. You can see how the `ask()` method works by looking at any of the implementations inside of the `vectorsearch/*` classes.

Expected behavior:
```ruby
Recipe.ask(question: "...")

# Top results are fetched from the vectorsearch DB and inserted as a context

# LLM produces a response
```

**Comment by andreibondarev** [comment]
@yorzi Want to take a stab at this?

**Comment by yorzi** [comment]
@andreibondarev Yeah, let me start from this one.
