### ISSUE TITLE
`chat.message("text")` response as LLM response not only Conversation::Response

### ISSUE THREAD

**Issue by misteral** [andreibondarev/langchainrb#348]
Now, it to respond with Conversation::Response. Perhaps a better approach would be to obtain the complete LLM response (LLM::BaseResponse).

There might be an alternative method to obtain the complete LLM response, as I should have the capability to calculate usages for the conversation.

I am ready to create PR for it, just give me better way.

**Comment by andreibondarev** [comment]
@misteral Feel free to suggest a PR!

**Comment by misteral** [comment]
Looks like it broke main your logic. Close now until better time
