### ISSUE TITLE
Would Adding Support for LCEL (Langchain Expression Language) Be Beneficial?

### ISSUE THREAD

**Issue by eLafo** [andreibondarev/langchainrb#369]
I've been using (python) Langchain and am interested in transitioning to langchainrb, mainly because of my love for Ruby.

I was wondering if adding support for [LCEL(Langchain Expression Language)](https://python.langchain.com/docs/expression_language/) to langchainrb would be a good idea to enhance its capabilities. I've considered continuing with Langchain, but my preference for Ruby makes langchainrb a more compelling option for me.

Would adding LCEL be beneficial?

I'd also like to offer my help in implementing this feature if the community thinks it's a good idea.

**Comment by ZhenhangTung** [comment]
The goal of LCEL is "chaining" components, right? I can use this feature, for I need to chain ChatGPT and DALL·E 3. As far as I understand, this chain concept hasn't been implemented. Correct me if I'm wrong. Agents will be less ideal for me, for I know the exact execution order and don't require LLMs to decide.

**Comment by andreibondarev** [comment]
@eLafo I don't think LCEL would be beneficial as this project has been (and will continue) drifting away from the Py/JS versions. I think we'll continue "leaning into" the Ruby/Rails community.
