### ISSUE TITLE
Support AWS Bedrock

### ISSUE THREAD

**Issue by fdaugs** [andreibondarev/langchainrb#383]
[Amazon Bedrock](https://aws.amazon.com/bedrock/) is a fully managed service that makes FMs from leading AI startups and Amazon available via an API, so you can choose from a wide range of FMs to find the model that is best suited for your use case.([Reference Langchain Component](https://python.langchain.com/docs/integrations/llms/bedrock))

**Comment by fdaugs** [comment]
I'm going to add this and open PR soon 👍

**Comment by andreibondarev** [comment]
@fdaugs This would be great! A colleague was literally asking me this week whether we integrated with AWS Bedrock. Thank you in advance! 🎉

**Comment by andreibondarev** [comment]
@fdaugs I think it's safe to close this issue for now?

**Comment by fdaugs** [comment]
Yes sure!
