### ISSUE TITLE
Gem 0.7.4 release corrupted causing eager autoloading to fail

### ISSUE THREAD

**Issue by mathieuripert** [andreibondarev/langchainrb#390]
### Context
- gem version `0.7.4` added  in a rails `7.0.6` application
- eager autoloading enabled when running continuous integration (cf `config.eager_load = ENV["CI"].present?`)

It appears that the gem release is corrupted with a file `gems/langchainrb-0.7.4/lib/langchain/loader_chunkers/html.rb` that is not in source code. And this file is causing the following error

```
NameError:
  uninitialized constant Langchain::LoaderChunkers::Base

      class HTML < Base
```

This prevents from autoloading  the entire rails app. (Also reproducible with `rails zeitwerk:check` in dev)

**Comment by andreibondarev** [comment]
D'oh! Give me a few minutes, I'll yank the 0.7.4 release and issue a new one.

**Comment by andreibondarev** [comment]
@mathieuripert Apparently rubygems doesn't let you re-push the yanked version again. So I'm cutting a new 0.7.5 release right now.

**Comment by andreibondarev** [comment]
It's published: https://rubygems.org/gems/langchainrb

**Comment by mathieuripert** [comment]
> It's published: https://rubygems.org/gems/langchainrb

awesome ! thanks
