### ISSUE TITLE
GooglePalm missing llm_options

### ISSUE THREAD

**Issue by mattlindsey** [andreibondarev/langchainrb#409]
I tried to initialize the llm like this
```ruby
llm = Langchain::LLM::GooglePalm.new(api_key: ENV["GOOGLE_PALM_API_KEY"], llm_options: {temperature: 0.2})`
```
but llm_options seems to unimplemented

https://github.com/andreibondarev/langchainrb/blob/719532ad264145346256b114c66f9c29df1f1b80/lib/langchain/llm/google_palm.rb#L26

**Comment by andreibondarev** [comment]
@mattlindsey Can you try passing it via default_options: {}?

**Comment by mattlindsey** [comment]
Ahhh. That seems to work. It's a little confusing since OpenAI had both parameters, and only changes defaults if default_params is passed.  I will always pass them, so it's fine with me.
