### ISSUE TITLE
Support for pgvector

### ISSUE THREAD

**Issue by ProGM** [andreibondarev/langchainrb#41]
[pgvector](https://github.com/pgvector/pgvector) is an extension for PostgreSQL that allows querying and indexing vector data.

There's already a gem for [ruby](https://github.com/pgvector/pgvector-ruby) and for [Rails](https://github.com/ankane/neighbor).

P.S. I've already implemented it on [GPTCache](https://github.com/zilliztech/GPTCache/pull/339), if you need I may help with this.

**Comment by andreibondarev** [comment]
@ProGM Thank you for filing this issue. Would you expect it to work exactly the same as the other supported Vector DBs?

I think there's some interesting questions to answer like whether we'd want to actually bring the whole ActiveRecord over (or another ORM) to interface with PSQL to support pgvector or other DBs in the future?

**Comment by ProGM** [comment]
Hi @andreibondarev,
It should be very similar to other Vector DBs. I've implemented myself a port from Milvus to pgvector and it's pretty effortless.

Here's a random untested implementation:
```ruby
# frozen_string_literal: true

module Vectorsearch
  class PgVector < Base
    def initialize(url:, index_name:, llm:, llm_api_key:, api_key: nil)
      require "pg"
      require "pgvector"

      registry = PG::BasicTypeRegistry.new.define_default_types
      Pgvector::PG.register_vector(registry)
      conn.type_map_for_results = PG::BasicTypeMapForResults.new(conn, registry: registry)

      @client = ::PG.connect( url: url )
      @index_name = index_name

      super(llm: llm, llm_api_key: llm_api_key)
    end

    def add_texts(texts:)
      texts.each do |text|
        client. exec_params(<<~SQL
          INSERT INTO #{@index_name} VALUES (NULL, $1, $2);
        SQL
        , [text, llm_client.embed(text: text)]
        )
      end
    end

    # Create default schema
    # @return [Hash] The response from the server
    def create_default_schema
      client.exec('CREATE EXTENSION IF NOT EXISTS vector;')
      client.exec(<<~SQL
      CREATE TABLE IF NOT EXISTS #{@index_name} (
	id serial PRIMARY KEY,
        content TEXT,
        vectors VECTOR(#{default_dimension}
      );
      SQL
     )
    end

    def similarity_search(query:, k: 4)
      embedding = llm_client.embed(text: query)

      similarity_search_by_vector(
        embedding: embedding,
        k: k
      )
    end

    def similarity_search_by_vector(embedding:, k: 4)
      client. exec_params(<<~SQL
         BEGIN;
         SET LOCAL ivfflat.probes = 10;
         SELECT * FROM #{@index_name} ORDER BY vector <-> $1 ASC LIMIT $2;
         COMMIT;
         SQL
       , [embedding, k]
      )
    end
  end
end
```


About the ActiveRecord yes / ActiveRecord no theme, my two cents:

I'll probably choose to use ActiveRecord, because:
a) It's opt-in: you can lazy-load active_record only if you choose the to use pgvector ad vector store.
b) It handles a LOT of stuff, also useful for future implementations (i.e. vector columns for [sqlite](https://observablehq.com/@asg017/introducing-sqlite-vss) or other SQL dbs in the future)
d) It's Rails-ready
e) If someone don't want ActiveRecord, it can just implement it's own adapter (it's not much effort, as you've seen in the code snippet)

**Comment by andreibondarev** [comment]
@ProGM Wow, amazing! Would you have any interest in submitting a PR since you've already implemented most of it?

**Comment by ProGM** [comment]
@andreibondarev yup! With or without ActiveRecord?

**Comment by rickychilcott** [comment]
I'd vote WITH AR for now.

**Comment by andreibondarev** [comment]
I'm actually thinking without the AR for now. Let me explain my reasoning...

I'm thinking that we start as lean as possible. I think the proper abstractions (and the whole DSL to this gem) are still emerging, and will become much more apparent and obvious with time.

Let's say we bring the AR over -- along with it we're bringing over Migrations, Tasks, Associations, Callbacks, Models, Validations, Querying, Schema Management, etc, etc. Do we intend to use these? Maybe! But let's make a deliberate case about using all of the AR tools! 

For example if you look at some of the current Vectorsearch wrappers under [/vectorsearch](https://github.com/andreibondarev/langchainrb/blob/main/lib/vectorsearch/), you can see ([here](https://github.com/andreibondarev/langchainrb/blob/main/lib/vectorsearch/weaviate.rb#L43-L59)) and [here](https://github.com/andreibondarev/langchainrb/blob/main/lib/vectorsearch/milvus.rb#L35-L69)) that we're creating static schemas which, I think, will change because they're too "opinionated". I think we ought to give the Dev more flexibility down the road. If we use ActiveRecord then we could have it run the migration and generate the ActiveRecord model on the fly:
```ruby
klass = Class.new(ActiveRecord::Base) do
  ...
```

**Comment by ProGM** [comment]
Hey @andreibondarev 
Consider that (python) langchain is using sql alchemy under the hood, both for [pgvector integration](https://github.com/hwchase17/langchain/blob/d4fd58963885465fba70a5cea9554a7b043b02a1/langchain/vectorstores/pgvector.py#L1) and for [SQLDataseChain](https://github.com/hwchase17/langchain/blob/d4fd58963885465fba70a5cea9554a7b043b02a1/langchain/chains/sql_database/base.py#L22).

I think that the reason is: it adds some abstraction from all the database vendors.


About the ActiveRecord implementation... yes, I think you may need to declare a model in runtime (or better: declare it statically and require it dynamically). We may also need to create a [dedicate connection](https://stackoverflow.com/a/17312606), to avoid interfering with other connections/databases.

---

However, I agree with you: let's start lean. I don't think that converting my code to ActiveRecord later will be such a big deal.

Just one final question:

How do we handle connection pooling? (are we even going to handle connection pooling in the first place?)

**Comment by andreibondarev** [comment]
@ProGM From your code:
```ruby
      @client = ::PG.connect( url: url )
```
This is what would instantiate a new connection.

I don't think we'd see any issues but of course I can't be 100% sure of it.

**Comment by ProGM** [comment]
@andreibondarev 
For Connection Pooling I mean something like this:

https://github.com/mperham/connection_pool

Maybe it's a bit premature, but it helps to improve availability.

However, I'm on the PR, I'm opening it soon :)

**Comment by andreibondarev** [comment]
@ProGM I would probably keep it simple but that's a great gem, we should definitely bookmark it for later.

**Comment by ProGM** [comment]
No problem, I can handle this ;)
It was just a question

**Comment by andreibondarev** [comment]
Agreed... it's common to pull in redis, psql, etc. containers to test in CI environments. But maybe locally we could continue mocking those services.

**Comment by ZhenhangTung** [comment]
I believe this feature would be supported by Heroku users. Please see this issue: https://github.com/heroku/roadmap/issues/156. 
I'm in the middle of deciding which vector DB should I use and I would expect myself facing same challenges, for I prefer using Heroku instead of AWS.

**Comment by ZhenhangTung** [comment]
From marketing perspective, we could first target Heroku users and see if they have any pain point that could be solved by langchainrb. Many of them are indie hackers, who could be our frameworks' early adopters.

**Comment by andreibondarev** [comment]
Yeah, that would be awesome! @ProGM was nice enough to put a PR together that is pretty close to being merged.
