### ISSUE TITLE
Allow specifying Ollama HTTP timeout settings

### ISSUE THREAD

**Issue by nossidge** [andreibondarev/langchainrb#421]
### Issue

The Ollama LLM uses the `faraday` gem to handle HTTP requests. And Faraday, using `Net::HTTP`, has a default `open_timeout` and `read_timeout` of 60 seconds. (https://github.com/lostisland/faraday/issues/708#issuecomment-477614664)

This has not always been enough time for the Ollama LLM to respond, on slower machines and larger responses.

### My hacky patch

I've solved this in my local code, by just monkey-patching the `Langchain::LLM::Ollama#client` private method to add `conn.options.timeout = 1000`:

```ruby
module Langchain::LLM
  class Ollama < Base
    private def client
      @client ||= Faraday.new(url: url) do |conn|
        conn.options.timeout = 1000
        conn.request :json
        conn.response :json
        conn.response :raise_error
      end
    end
  end
end
```

### Potential fix

It seems like faraday is only ever used in the code for the `Ollama` LLM, so something like this should allow for specifying the timeout:

```ruby
module Langchain::LLM
  class Ollama < Base
    attr_reader :url, :timeout

    # Initialize the Ollama client
    # @param url [String] The URL of the Ollama instance
    # @param timeout [Integer] The timeout in seconds of the HTTP request. Default is 60, set by `Net::HTTP`
    def initialize(url:, timeout:)
      @url = url
      @timeout = timeout
    end

    # ...

    def client
      @client ||= Faraday.new(url: url) do |conn|
        conn.options.timeout = timeout
        conn.request :json
        conn.response :json
        conn.response :raise_error
      end
    end
  end
end
```

But I'm hesitant to open a PR changing this public interface, and I'm aware that this is something that should be documented somewhere, specifically that it's inherited from `Net::HTTP` (in case that value ever changes).

**Comment by andreibondarev** [comment]
@nossidge Hmm... I don't really see any options other than modifying the Ollama class. Is it possible to globally modify `Faraday.default_connection.options.timeout` or `Net::HTTP` and set the timeouts application wide?

**Comment by nossidge** [comment]
Yep, it is possible!

I did some [further searching](https://stackoverflow.com/a/53713507) and discovered this:
```ruby
Faraday.default_connection_options = Faraday::ConnectionOptions.new({timeout: 1000})
```
If I run that config line before I run the prompt generation line, it does not timeout.

Solved, and thanks for listening!
