### ISSUE TITLE
Add the `Ollama#chat()` method

### ISSUE THREAD

**Issue by andreibondarev** [andreibondarev/langchainrb#423]
Ollama now supports the `chat()` endpoint: https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-a-chat-completion
Please add the method to the Ollama LLM.

**Comment by spikex** [comment]
On it.

**Comment by andreibondarev** [comment]
> On it.

@spikex I went ahead and implemented it here: https://github.com/andreibondarev/langchainrb/pull/457. I hope you didn't waste too much time already implementing it!

**Comment by spikex** [comment]
Sorry, got hung up on testing streaming and then pulled into other things. Thanks for getting it done!

Looks like it's now possible to use the OpenAI APIs with Ollma as well.

https://ollama.ai/blog/openai-compatibility
