### ISSUE TITLE
New GPT-4-0125-preview ArgumentError

### ISSUE THREAD

**Issue by johnknapp** [andreibondarev/langchainrb#448]
After switching from `gpt-4-1106-preview` to the new `gpt-4-0125-preview`, there is a `langchainrb ArgumentError`:

```
ArgumentError: unknown keyword: :prompt (ArgumentError)
        /gems/langchainrb-0.9.0/lib/langchain/llm/openai.rb:93:in `chat'
```

The error occurs when my code says:

`raw = @llm.chat(prompt: prompt).completion`

(Which has been working fine with the earlier model.)

**Comment by johnknapp** [comment]
I was wrong. My code gave birth to a new bug over night.

**Comment by andreibondarev** [comment]
@jaemo Are you using OpenAI? If so -- that interface was changed recently. I probably didn't handle it the ideal way...

**Comment by jaemo** [comment]
@andreibondarev Yes, and as a data point, if it is helpful, I've rolled back to 0.8.2 and it's working normally there.

**Comment by andreibondarev** [comment]
@jaemo This is going to be the fix: https://github.com/andreibondarev/langchainrb/pull/454 but I'd like to rewrite all of the LLM#chat() methods to accept the `messages:` param.
