### ISSUE TITLE
langchain/llm/ollama.rb NameError: uninitialized constant Langchain::LLM::Ollama::Faraday

### ISSUE THREAD

**Issue by ttilberg** [andreibondarev/langchainrb#458]
- In the Ollama client, Faraday is assumed to be autoloaded, which is not likely the case when outside of Rails
- Faraday also does not show up in the gem dependencies, and therefor must be installed separately, even though the constant is directly referenced in [this code](https://github.com/andreibondarev/langchainrb/blob/005c39b38b8d15bd0d0ed40cb819fb61d749d24d/lib/langchain/llm/ollama.rb#L217).

I see that Faraday appears in the Gemfile for the project, so tests pass when doing development, but do not work through gem distribution. Additionally, `require 'faraday'` is in the test file, but should also be in the client file to play nicely without Rails.

```
▶ gem install pry langchainrb
Fetching pry-0.14.2.gem
Successfully installed pry-0.14.2
Parsing documentation for pry-0.14.2
Installing ri documentation for pry-0.14.2
Done installing documentation for pry after 0 seconds
Fetching langchainrb-0.9.0.gem
Successfully installed langchainrb-0.9.0
Parsing documentation for langchainrb-0.9.0
Installing ri documentation for langchainrb-0.9.0
Done installing documentation for langchainrb after 0 seconds
2 gems installed

~
▶ pry
[1] pry(main)> require 'langchainrb'
=> true
[2] pry(main)> llm = Langchain::LLM::Ollama.new(url: 'http://localhost:11434')
=> #<Langchain::LLM::Ollama:0x000000011fb59918 @url="http://localhost:11434">
[3] pry(main)> llm.complete(prompt: "Hello world", model: "mistral")
NameError: uninitialized constant Langchain::LLM::Ollama::Faraday
from /Users/ttilberg/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/langchainrb-0.9.0/lib/langchain/llm/ollama.rb:84:in `client'
[4] pry(main)> require 'faraday'
LoadError: cannot load such file -- faraday
from <internal:/Users/ttilberg/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
```

**Comment by ttilberg** [comment]
Regarding not including Faraday in Gemspec, I see that other client libs (such as AWS) are also not included. I can see how this makes sense to keep unused client libs at bay, but it would be helpful to include information on optional dependencies required for additional clients in the Readme.

**Comment by andreibondarev** [comment]
@ttilberg Thank you! Would you like to open up a PR with a fix?

**Comment by ttilberg** [comment]
You bet. I'll leave followup questions in the pr.
