### ISSUE TITLE
Updating the gem?

### ISSUE THREAD

**Issue by johnknapp** [andreibondarev/langchainrb#463]
gem 0.9.0 is a few weeks old and there have been some important things merged since then.

What's the process to update the gem?

**Comment by source-labs-llc** [comment]
Oh!

* Bump the version to 0.9.1
* Add to the CHANGELOG.md
* bundle install
* Push the changes and open the PR
* I’ll do the rest

-Andrei

*Source Labs LLC*
*www.sourcelabs.io <http://www.sourcelabs.io/>*
*Cell: 703-347-4980 <(703)%20347-4980>*
*LinkedIn: *https://www.linkedin.com/in/andreibondarev/

**Comment by johnknapp** [comment]
Done. [On PR 464](https://github.com/andreibondarev/langchainrb/pull/464). Closing
