### ISSUE TITLE
Vectorsearch::Pinecone#ask broken on 0.9.x

### ISSUE THREAD

**Issue by mrz944** [andreibondarev/langchainrb#466]
Adding Assistants seems to broke existing Vectorsearch.

`LLM::OpenAI#chat` no longer accept prompts from `Vectorsearch`
https://github.com/andreibondarev/langchainrb/commit/4ec3c8f44a355c6b09291c1a694df92c73576cf3#diff-e9b54ad7b6ef063bedb31fba426cea87e7b816d4eeaa65a4ffb07929e6e58646R90

https://github.com/andreibondarev/langchainrb/blob/4f83f1c28740e695fe659f6f93df70064eef4abe/lib/langchain/vectorsearch/pinecone.rb#L183

This affects also other Vectorsearches than Pinecone.

**Comment by andreibondarev** [comment]
@mrz944 This should be fixed now!

**Comment by mrz944** [comment]
It's working perfectly now. Thanks!
