### ISSUE TITLE
Bump version dependency on `colorize`

### ISSUE THREAD

**Issue by huerlisi** [andreibondarev/langchainrb#475]
The dependency on `colorize` triggered a downgrade of that gem in our code base when adding `langchainrb`.

I believe the newest major version `1.1.0` is compatible with this gem and would appreciate if you could bump the requirement.

**Comment by huerlisi** [comment]
@andreibondarev we did downgrade and it's no issue.

We just like to keep gems up-to-date. No hurry with a fix:-)

**Comment by andreibondarev** [comment]
@huerlisi Could you please issue the PR with the fix?
