### ISSUE TITLE
OpenAI Dimension size's aren't passed to Ruby Gem or used when creating vector store collection

### ISSUE THREAD

**Issue by prdanelli** [andreibondarev/langchainrb#488]
Now that `text-embedding-3-small` (and large) is available, we can utilise smaller dimension vector embeddings. However, it seems that the dimension value was not being passed to the OpenAI gem, as all embed requests returned 1536 vectors, irrespective of the dimension size requested. 

I've created a PR that resolves the issues here: 
https://github.com/andreibondarev/langchainrb/pull/487

**Comment by andreibondarev** [comment]
@prdanelli It's fixed now.

**Comment by emezac** [comment]
Yeap similar to this one: https://github.com/andreibondarev/langchainrb/issues/506
