### ISSUE TITLE
similarity_search_with_hyde breaking

### ISSUE THREAD

**Issue by sushantbhanot84** [andreibondarev/langchainrb#490]
data = client.similarity_search_with_hyde(query: "What is langchain", k: 4)
/home/sushant/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/langchainrb-0.9.3/lib/langchain/llm/openai.rb:53:in `embed': undefined method `empty?' for #<Langchain::LLM::OpenAIResponse:0x000055f028dde398

**Comment by andreibondarev** [comment]
@sushantbhanot84 It's fixed now.
