### ISSUE TITLE
Rails 7.0.x no longer supported

### ISSUE THREAD

**Issue by prdanelli** [andreibondarev/langchainrb#497]
It seems as though [this commit](https://github.com/andreibondarev/langchainrb/commit/ca952d542dc3733dd8647eae065683f4075ddecc) has enforced Rails 7.1 usage. Rails 7.0.8 is still being actively supported, is it possible to allow both?

**Comment by andreibondarev** [comment]
Yeah, I'm actually thinking we should've stuck with that `deep_merge` gem instead of pulling `activesupport` in: https://github.com/andreibondarev/langchainrb/pull/494#issuecomment-1966557305

**Comment by prdanelli** [comment]
@andreibondarev I've created a quick and dirty PR to add back support. All the specs are passing locally. 

https://github.com/andreibondarev/langchainrb/pull/498
