### ISSUE TITLE
Parameter 'dimensions' are not using anymore  for embbedings.

### ISSUE THREAD

**Issue by emezac** [andreibondarev/langchainrb#506]
Test:
curl https://api.openai.com/v1/embeddings \                                                                
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer AP”I_KEY \
  -d '{
    "input": "Your text string goes here", \
    "model": "text-embedding-ada-002”,\
  }'

Please check : https://platform.openai.com/docs/api-reference/chat/create 

My quick fix over : lib/langchain/llm/openai.rb:
 ```ruby
    def embed(
      text:,
      model: defaults[:embeddings_model_name],
      encoding_format: nil,
      user: nil,
      dimensions: nil # if we expect it to be explicitly passed
    )
      raise ArgumentError.new("text argument is required") if text.empty?
      raise ArgumentError.new("model argument is required") if model.empty?
      raise ArgumentError.new("encoding_format must be either float or base64") if encoding_format && %w[float base64].include?(encoding_format)

      # Warning about the obsolete `dimensions` parameter
      if dimensions
        warn "Warning: The 'dimensions' parameter is obsolete and no longer used. The embedding dimension will automatically be determined based on the selected model."
      end

      parameters = {
        input: text,
        model: model,
        # The `dimensions` parameter is no longer included here
      }
      parameters[:encoding_format] = encoding_format if encoding_format
      parameters[:user] = user if user
```
```

**Comment by andreibondarev** [comment]
@emezac I think [here](https://github.com/andreibondarev/langchainrb/blob/main/lib/langchain/llm/openai.rb#L52C1-L66) what we should do is:
1. Add the `dimensions:` param back in:
```ruby
def embed(
  ...
  dimensions: nil
)
```
2. Use either what's passed in (an override) or use the defaults
```ruby
      parameters = {
        input: text,
        model: model,
        dimensions: dimensions || default_dimension
      }
```

```

**Comment by emezac** [comment]
Yeap that is a better approach.

**Comment by andreibondarev** [comment]
@emezac Would you be able to open a PR please? Please make sure to write tests as well.

@prdanelli Thought on this approach?

**Comment by emezac** [comment]
Yes I will

**Comment by spikex** [comment]
The `dimension` param now causes a error for the _text-embedding-ada-002_ model, however **can** be used with _text-embedding-3-small_ and _text-embedding-3-large_.

I would suggest:

- Making the `dimension` parameter nil by default, and just letting the API use its default.
- Making _text-embedding-3-small_ the default model, it's [cheaper and better](https://platform.openai.com/docs/guides/embeddings/embedding-models) than _text-embedding-ada-002_.
- Leaving the `model` param, as we do have options now.

**Comment by andreibondarev** [comment]
> Leaving the model param, as we do have options now.
@spikex What did you mean here? The rest of your changes were done in the linked PR btw.

**Comment by spikex** [comment]
There was a comment above suggesting removing the model param. All good.
