### ISSUE TITLE
require "mail" in Langchain::Processors::Eml breaks dependency loader

### ISSUE THREAD

**Issue by ipepe** [andreibondarev/langchainrb#518]
`Langchain::Processors::Eml` has a `require "mail"` but it also has a 

```ruby
      def initialize(*)
        depends_on "mail"
      end
```

Which doesn't make any sense in case I do not want to process `eml` files and don't have `mail` library available. 

`require "mail"` should be removed from the top line in `langchain/processors/eml.rb`

**Comment by andreibondarev** [comment]
@ipepe Good call, should be fixed now.
