### ISSUE TITLE
Zeitwerk::NameError in production

### ISSUE THREAD

**Issue by andreaslillebo** [andreibondarev/langchainrb#532]
When trying to run a Rails-app in production, I get the following error:

> /Users/andreas/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/callbacks.rb:33:in `on_file_autoloaded': expected file /Users/andreas/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/langchainrb-0.9.5/lib/langchain/tool/ruby_code_interpreter/ruby_code_interpreter.rb to define constant Langchain::Tool::RubyCodeInterpreter, but didn't (Zeitwerk::NameError)

Rails: 7.1.3.2
Ruby: 3.3.0
Langchainrb: 0.9.5 or greater (0.9.4 works fine)

The issue seems to be related to the following conditional:
https://github.com/andreibondarev/langchainrb/blob/18979618ec19ff65a9acd047a5e43e1998c12049/lib/langchain/tool/ruby_code_interpreter/ruby_code_interpreter.rb#L5-L7

**Comment by lebedevilya** [comment]
same

**Comment by andreibondarev** [comment]
This happens during app start-up, right? As in -- you're not calling that tool directly.

**Comment by andreaslillebo** [comment]
> This happens during app start-up, right? As in -- you're not calling that tool directly.

Yes

**Comment by andreaslillebo** [comment]
@andreibondarev, I created a PR that appears to fix the issue. This would also make #533 redundant.
