### ISSUE TITLE
Zeitwerk::NameError (RicardosCoffeeMaker)

### ISSUE THREAD

**Issue by andreaslillebo** [andreibondarev/langchainrb#536]
This may be one of the most bizarre bugs I've ever encountered ...

When trying to run a Rails-app in production, I get the following error:

> expected file /Users/andreas/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/langchainrb-0.10.1/lib/langchain/tool/ricardos_coffee_maker/ricardos_coffee_maker.rb to define constant Langchain::Tool::RicardosCoffeeMaker::RicardosCoffeeMaker, but didn't

Can be quickly reproduced by running `rails zeitwerk:check`.

Rails: 7.1.3.2
Ruby: 3.3.0
Langchainrb: 0.10.1

I can't find anything in this repo about `RicardosCoffeeMaker`, but when downloading the gem from [rubygems.org](https://rubygems.org/gems/langchainrb/versions/0.10.1), unpacking with `gem unpack`, there is indeed an empty ruby-file (ricardos_coffee_maker.rb) and JSON-file (ricardos_coffee_maker.json). This is not the case for version 0.10.0.

☕️🤔

**Comment by andreibondarev** [comment]
@andreaslillebo I'll yank out 0.10.1 and re-publish right now.
