### ISSUE TITLE
[Proposal] Change method add_data's parameter

### ISSUE THREAD

**Issue by ZhenhangTung** [andreibondarev/langchainrb#62]
Under module `Vectorsearch::Base`, there is a method `add_data` accepting `path: nil, paths: nil` params. 
From my point of view, we could remove `path` and only accept `paths` or use the [splat operator](https://medium.com/@sologoubalex/parameter-with-splat-operator-in-ruby-part-1-2-a1c2176215a5).

**Comment by andreibondarev** [comment]
@ZhenhangTung I'll let the @rickychilcott chime in as he built the original implementation. I don't have a preference here.

**Comment by rickychilcott** [comment]
I'd be supportive of it becoming:

```ruby
def add_data(paths:)
  texts = 
    Array(paths)
      .map { |path| Langchain::Loader.new(path)&.load&.value }
      .compact

  add_texts(texts: texts)
end
```

I'd like to keep the named parameter:

a) to be consistent with the API elsewhere in the class
b) to provide an opportunity to support other arguments

**Comment by ZhenhangTung** [comment]
@rickychilcott Great!

**Comment by andreibondarev** [comment]
@ZhenhangTung Would you have any interest and availability to open up a PR for this?

**Comment by ZhenhangTung** [comment]
@andreibondare That would be my honor.
