### ISSUE TITLE
Data stored with pgvector is not indexed

### ISSUE THREAD

**Issue by ProGM** [andreibondarev/langchainrb#67]
Starting from #55, copying here for reference:

pgvector specifies [in the docs](https://github.com/pgvector/pgvector#indexing) that the index must be defined AFTER the table has some data inside. So even if I would define it during schema creation, it won't have any effect on performances. You must create (or reindex) it AFTER you've put data in the table.

Solutions:
a) Add a method like update_indexes that the user must call manually after adding data
b) Update the index implicitly in the add_texts method, maybe with an option (update_index: true)

**Comment by ZhenhangTung** [comment]
In the context of Rails, I'll use migrations to create index instead of code. All changes on db schema will be tracked, which makes me feel safe.
So to me, it doesn't matter if this feature is provided or not.

**Comment by ZhenhangTung** [comment]
> I’m not sure that Langchain rb needs to own this concern. I definitely would not advocate for solution B. A convenience method such as solution A is nice, but I don’t see it as necessary. Simply calling the issue out in the docs and perhaps a link to an article or sql snipped to add indexes is all this is “needed”

Agree with @rickychilcott .
It's a great example of discussing what we need to do and what we don't. 
From my perspective, Langchain's goal is to provide an abstraction layer of agents, vector databases, etc, so the bar of building LLM-driven apps could be lower. From this angle, this feature may not be in the scope of Langchain's responsibility. So better to let users manage the index themselves or let [the client](https://github.com/pgvector/pgvector-ruby) take care of it. If we create a db index implicitly, I guess users would be "surprised" and new issues would be opened soon 🤣 .

**Comment by andreibondarev** [comment]
Agreed. I'm closing this issue for now; We can re-open it later if needed.

**Comment by ProGM** [comment]
@andreibondarev 

Fine, I agree with your verdict, it totally makes sense.

Evolving the discussion: if creating/maintaining the index out of scope of this library, why are we even creating the table schema in the first place?

Maybe a good approach could be to just pass the name of the table (and the columns?) and Langchain just runs the queries on it?
