### ISSUE TITLE
Add missing specs for Qdrant.

### ISSUE THREAD

**Issue by andreibondarev** [andreibondarev/langchainrb#72]
We're missing the specs for the Qdrant vectorsearch.

Tasks:
- Add `spec/vectorsearch/qdrant_spec.rb` with specs.

**Comment by akmhmgc** [comment]
@andreibondarev 

Thanks for great repository!!
May I work on this issue??

**Comment by andreibondarev** [comment]
@akmhmgc Please! We would appreciate your contribution very much!
