### ISSUE TITLE
Move all of the custom errors/exceptions to a dedicated file

### ISSUE THREAD

**Issue by andreibondarev** [andreibondarev/langchainrb#79]
## Problem
We currently have custom errors/exceptions spread out and defined all throughout the project within different namespaces.

## Solution
Gather up and move all of the custom error class definitions to a dedicated `errors.rb` file. Here's an example of a good organization: https://github.com/jnunemaker/httparty/blob/master/lib/httparty/exceptions.rb. Please annotate (write documentation) to each error class, when it's raised, etc.

**Comment by technicalpickles** [comment]
There don't seem to be a ton of classes yet, I see 4:

 https://github.com/andreibondarev/langchainrb/blob/7df1a227567a50dad2dc1d45065f747a13034576/lib/dependency_helper.rb#L3

https://github.com/andreibondarev/langchainrb/blob/7df1a227567a50dad2dc1d45065f747a13034576/lib/langchain/loader.rb#L7-L9

https://github.com/andreibondarev/langchainrb/blob/7df1a227567a50dad2dc1d45065f747a13034576/lib/langchain/utils/token_length_validator.rb#L7

I think httparty is a lot more narrowly defined, where everything has to do with http in some form. For langchainrb, they can be quite different concerns.

The only benefit I can think of off hand is that they would be all in one place, and if we do API docs, they'd be in the same place as well.

> Please annotate (write documentation) to each error class, when it's raised, etc.

Seems like a good exercise regardless of collacting them 😁

**Comment by andreibondarev** [comment]
Valid points. I was trying to look ahead and force a pattern to follow.

I think it's either -- single file:
```
langchain/errors.rb
```
or an errors file per folder:
```
vectorsearch/errors.rb
llm/errors.rb
# etc
```

**Comment by technicalpickles** [comment]
The per folder makes sense to me, ie grouping under vectorstore, llm, etc.

Surprisingly, we don't have errors under those folders. I think as things move along, we'd want to make sure errors from libraries we use for those wrap in a langchain-specific error. That would help make sure  it's easier to move from one LLM / vectorstore to another.
