### ISSUE TITLE
An abstraction that interfaces with a database and uses an LLM to come up with SQL queries to be executed.

### ISSUE THREAD

**Issue by andreibondarev** [andreibondarev/langchainrb#80]
## Background
A popular use-case is constructing a prompt for the LLM that includes the database schema, and user's question at hand to construct a SQL query that gets executed on LLM's behalf. The SQL query's result then gets fed back to the LLM to synthesize an answer to the user's question.

 ## Objectives
Create an entity (should it be a Tool? an Agent? or another abstraction?) that:
- Can establish a connection to a database
- Can execute (sanitized!) SQL queries
- Can construct a prompt for the LLM that:
  - Includes information about the DB schema, or only relevant tables? Subject to context window limits.
  - Includes the instructions for the LLM
  - Includes the user's question.
  - Good prompt to model after: [link](https://github.com/jerryjliu/llama_index/blob/35aa5bee71a6f7ef6e1c331a2f7528dfc52b7ffc/llama_index/prompts/default_prompts.py#L171-L192).

**Comment by ZhenhangTung** [comment]
@andreibondarev I'll try to rephrase the challenge to make sure I understand it correctly. What we want to build is an abstraction that take user's question as input and return LLM's response as output. During this process, we will connect to the db searching texts that share similar semantic meaning and use them as prompt's context. If that's the case, we could consider implementing [RetrevalQA](https://blog.langchain.dev/retrieval/)?
