### ISSUE TITLE
Pgvector integration `similarity_search_by_vector()` should use the cosine distance by default

### ISSUE THREAD

**Issue by andreibondarev** [andreibondarev/langchainrb#86]
The Pgvector's `similarity_search_by_vector()` should be calculating the cosine distance by default: https://github.com/andreibondarev/langchainrb/blob/main/lib/vectorsearch/pgvector.rb#L75-L77

More info about building a cosine distance query here: https://github.com/pgvector/pgvector/blob/dee2c4feb1bc5b17b9fe6a0a1ce8dbf0963c1b05/README.md#vector-operators

**Comment by ProGM** [comment]
@andreibondarev 
If you need help I may take a look into this ^^

**Comment by andreibondarev** [comment]
@ProGM That would be great! Thank you!

**Comment by ProGM** [comment]
@andreibondarev PR opened at #90 ;)
