### ISSUE TITLE
Pgvector integration: Wrap `@index_name` in `quote_ident(@index_name)` in all queries

### ISSUE THREAD

**Issue by andreibondarev** [andreibondarev/langchainrb#87]
### Tasks:
Wrap all of the instances of `@index_name` inside of queries in a `quote_ident(@index_name)`. More information about quote_ident: https://www.rubydoc.info/gems/pg/PG/Connection#quote_ident-instance_method

**Comment by ProGM** [comment]
@andreibondarev 
I can work on this as well ^^
